title: Technophile
subtitle: A Jekyll Theme for Technophiles, Developers and Hackers
description: >- # this means to ignore newlines until "baseurl:"
  technophile-jekyll is a Jekyll theme for Technophiles, Developers and Hackers to host their portfolio and blog

# url: "https://aquistech.github.io/technophile-jekyll" # the base hostname & protocol for your site, e.g. https://example.github.io
# baseurl: "https://aquistech.github.io/technophile-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Feature Toggles
blog_enabled: false
shop_enabled: false
newsletter_enabled: false
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# Navbar URLs
urls:
    - text: About Me
      url: /about
    # - text: Blog
    #   url: /blog
    # - text: NanoBlogs
    #   url: /nano-blog
    # - text: Tutorials
    #   url: /tutorials
    # - text: My Work
    #   url: /my-work
    # - text: Gallery
    #   url: /gallery
    # - text: Ask my cat
    #   url: /ask-me
    # - text: Quotes/Memes
    #   url: /quotes
    # - text: Shop
    #   url : /shop
    # - text: Contact Me
    #   url : /contact
    # - text: Styleguide
    #   url: /styleguide
    # - text: Get Started
    #   url: /get-started

# Edit these details
author: Technophile Jekyll
author_logo: profile.png
author_logo_style: circle # Available options are : full, square, circle
author_bio: Hey, my name is Technophile Jekyll. I built this site using technophile-jekyll !!!
author_location: India
author_contact_number: 123456789
author_email: "technophile-jekyll@example.com"
author_website_url: "https://aquistech.github.io/technophile-jekyll"
typewrite-text: technophile-jekyll is a Jekyll theme for Technophiles, Developers and Hackers to host their portfolio and blog

# About > Left column
# social links
github_username: technophile-jekyll
bitbucket_username: technophile-jekyll
linkedin_username: technophile-jekyll
stackoverflow_username: 12345/technophile-jekyll # Note: This will be in format as user_id/username
# hackerrank_username: technophile-jekyll # Hackerrank icon not available
twitter_username: technophile-jekyll
facebook_username: technophile-jekyll
instagram_username: technophile-jekyll
whatsapp_username: 1234567890 # This will be whatsapp number
# skype_username: technophile-jekyll # Not able to find profile link
behance_username: technophile-jekyll
medium_username: technophile-jekyll
telegram_username: technophile-jekyll
dribbble_username: technophile-jekyll
flickr_username: technophile-jekyll
youtube_username: technophile-jekyll # Note: This will be Youtube channel id
vimeo_username: technophile-jekyll # Note: This will be Vimeo user id
vimeo_channelname: technophile-jekyll # Note: This will be Vimeo channel id
# more possible additions
#- delicious https://del.icio.us/
#- devian arts
#- blogger
#- digg
#- dribble
#- pinterest
#- codepen
#- rubygems
# TODO: Provision for custom link

author_skills:
    primary:
      - Ruby
      - Rails
      - jRuby
      - Javascript
      - jQuery
    secondary:
      - HTML
      - CSS
      - Bootstrap
      - Zurb Foundation

author_hobbies:
  - Singing
  - Dancing
  - Trekking
  - Photography


# About > Right column
author_work_experiences:
    - company_name: Google
      company_logo: google.png
      company_url: https://google.com
      designation: Software Engineer
      description: Worked on various Google Products
      visibility: true
    - company_name: Microsoft
      company_logo: microsoft.png
      company_url: https://microsoft.com
      designation: Azure Developer
      description: Worked on various Azure Cloud Products
      visibility: true

author_education_details:
    - college_logo: mit.png
      college_name: MIT
      college_url: https://mit.org
      college_degree: CS Engineer
      description: Bachelor of Technology
      visibility: true
    - college_logo: iit.jpeg
      college_name: IIT
      college_url: https://mit.org
      college_degree: CS Engineer
      description: Bachelor of Technology
      visibility: true
    - college_logo: oxford.png
      college_name: Oxford
      college_url: https://mit.org
      college_degree: CS Engineer
      description: Bachelor of Technology
      visibility: true

author_project_details:
    - project_thumbnail: gamershub.png
      project_title: Gamers Hub
      project_description: A Platform built for Gamers and Game Devs
      project_url: https://gamershub.in
      visibility: true
    - project_thumbnail: hack4r.PNG
      project_title: Hack4r
      project_description: A Platform built for Hackers and Penetration Testers
      project_url: https://hack4r.com
      visibility: true
    - project_thumbnail: gamershub.png
      project_title: Gamers Hub
      project_description: A Platform built for Gamers and Game Devs
      project_url: https://gamershub.in
      visibility: true
    - project_thumbnail: hack4r.PNG
      project_title: Hack4r
      project_description: A Platform built for Hackers and Penetration Testers
      project_url: https://hack4r.com
      visibility: true

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: technophile-jekyll
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: technophile-jekyll

# mailchimp embedded form url (newsletter):
mailchimp_form_url: mailchimp_url_for_technophile-jekyll

# formspree (contact form)
formspree_email: johndoe@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
